#!/usr/bin/env python
import cgi
import cgitb
import os
import datetime

cgitb.enable()


default = "No Value Present"

print("Content-Type: text/html")
print("")

body = """<html>
<head>
<title>Lab 1 - CGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by <b>{software}</b>, running <b>{script}</b></p>
<p>Today is: <b>{month} {date}, {year}</b>.</p>
<p>This page was requested by IP Address: <b>{client_ip}</b></p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', default),
    script=os.environ['SCRIPT_NAME'],
    month=datetime.datetime.now().strftime('%B'),
    date=datetime.date.today().day,
    year=datetime.date.today().year,
    client_ip=os.environ['REMOTE_ADDR']
)
print(body)
